# Generated by Django 5.0.3 on 2024-03-20 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventMentors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventmentor_id', models.IntegerField()),
                ('approved', models.BooleanField(default=False)),
                ('event_onboarding_task', models.IntegerField(blank=True, null=True)),
                ('event_offboarding_task', models.IntegerField(blank=True, null=True)),
                ('role_requested', models.BooleanField(default=False)),
                ('role_assigned', models.BooleanField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('event_type', models.TextField()),
                ('event_name', models.TextField()),
                ('event_start_date', models.DateTimeField()),
                ('event_end_date', models.DateTimeField()),
                ('attendee_numbers', models.IntegerField()),
                ('location', models.TextField()),
                ('event_mentors', models.IntegerField()),
                ('is_open', models.BooleanField()),
                ('date_created', models.DateTimeField()),
            ],
        ),
    ]
