# Generated by Django 5.0.3 on 2024-03-20 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmentors',
            name='mentor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentored_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventmentors',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_user', to='events.events'),
        ),
    ]
