# Generated by Django 5.0.3 on 2024-03-21 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_mentors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.eventmentors'),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_start_date',
            field=models.DateField(),
        ),
    ]
