# fly.toml app configuration file generated for 2024_bit_by_bit_back_end on 2024-03-26T21:50:02+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '2024_bit_by_bit_back_end'
primary_region = 'syd'
console_command = '/code/manage.py shell'
kill_signal = "SIGINT"
kill_timeout = 5
processes = []


[build]

[env]
  PORT = '8000'

[[services]]
  http_checks = []
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/static/"

[mounts]
  source = "dbvol"
  destination = "/dbvol"


