# Generated by Django 5.0.3 on 2024-03-26 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_slack_alter_userprocess_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprocess',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userprocess',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarded_mentor', to=settings.AUTH_USER_MODEL),
        ),
    ]
