# Generated by Django 5.0.3 on 2024-03-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userprocess_user_id_userprocess_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprocess',
            name='user_offboarding_task',
        ),
        migrations.RemoveField(
            model_name='userprocess',
            name='user_onboarding_task',
        ),
        migrations.AddField(
            model_name='userprocess',
            name='user_offboarding_task_feedbackreceived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprocess',
            name='user_offboarding_task_feedbackrequested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprocess',
            name='user_offboarding_task_tshirtreceived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprocess',
            name='user_onboarding_task_CodeofConduct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprocess',
            name='user_onboarding_task_linkedin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprocess',
            name='user_onboarding_task_slack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprocess',
            name='user_onboarding_task_tshirtsent',
            field=models.BooleanField(default=False),
        ),
    ]
