# Generated by Django 5.0.3 on 2024-03-30 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userprocess_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprocess',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarded_mentor', to=settings.AUTH_USER_MODEL),
        ),
    ]
