# Generated by Django 5.0.3 on 2024-04-03 00:02

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userprocess_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profilepic',
            field=models.ImageField(blank=True, null=True),
        ),
    ]
