# Generated by Django 5.0.3 on 2024-03-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmentors',
            name='event_offboarding_task',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventmentors',
            name='event_onboarding_task',
            field=models.TextField(blank=True, null=True),
        ),
    ]
