# Generated by Django 5.0.3 on 2024-03-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_eventmentors_event_offboarding_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmentors',
            name='event_id',
        ),
        migrations.AddField(
            model_name='eventmentors',
            name='event_id',
            field=models.ManyToManyField(to='events.events'),
        ),
    ]
