# Generated by Django 5.0.3 on 2024-03-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_eventmentors_event_id_eventmentors_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmentors',
            name='role_requested',
            field=models.TextField(),
        ),
    ]
