# Generated by Django 5.0.3 on 2024-04-06 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_eventmentors_event_offboarding_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmentors',
            name='role_assigned',
            field=models.TextField(default='Unassigned'),
        ),
    ]
